### ISSUE TITLE
Restructure project structure

### ISSUE THREAD

**Issue by samundra** [foss-np/swatantra_krishi#2]
## Proposal

I would like to propose the following code restructure in the project:

- use git submodules to organize the various parts of the project

#### Proposed git submodule

```
Krishi
|-- swatantra-data-diff-sources
|-- swatantra-docs
|-- swatantra-app
|-- README.md

```

**Krishi** = Main project root directory
**swatantra-data-diff-sources** = Separate git repository included as git submodules
**swatantra-docs** = Separate git repository included as git submodules
**swatantra-app** = Separate git repository included as git submodules
**README.md** = Documentation for the project.

Please cast your vote with :+1: or :-1:  and we can discuss on it.

**Comment by srestaswrnm** [comment]
:+1:

**Comment by haxormad** [comment]
THANKS FOR IT...
